### ISSUE TITLE
'401 Unauthorized'  

### ISSUE THREAD

**Issue by dat0106** [m-lab/ndt7-client-android#10]
I got ERROR 
onError: java.net.ProtocolException: Expected HTTP 101 response but was '401 Unauthorized'
        at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

it seems this problem has only suffered a few days,
Has anyone fixed this problem yet?

**Comment by stephen-soltesz** [comment]
@dat0106 thank you for reporting this. This repo does not use the Locate API directly. What app or client are you using that depends on this library? There is some additional code that the caller will need to add independent of this repo. If you can help provide a pointer, we can try to let them know.

Because the access token requirement has broken this client and the ndt7-client-ios client, we've rolled back the [access token requirement][1]. However, only the ndt7-client-ios repo has code for accessing the Locate API. The ndt7-client-android sources apparently do not. So, we cannot update all clients before we restore the flag flip without a pointer.

[1]: https://github.com/m-lab/k8s-support/releases/tag/v2.21.2

**Comment by stephen-soltesz** [comment]
This is likely fixed by recent changes. Please let us know if there is still an issue. https://github.com/m-lab/ndt7-client-android/pull/9
